jobs:
  log_merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run log update script
        run: python merge_logging/update_merge_log.py

      - name: Commit and push updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add merge_logging/merge_logs.csv
          git commit -m "Update merge log"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
